FROM openjdk:8

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt update && apt install -y maven && apt install -y vim

# RUN cd /root/selogger/selogger && git clone https://github.com/takashi-ishio/selogger
# RUN cd selogger && mvn package -Dmaven.test.skip=true

