version: '3'
services:
  java8:
    restart: always
    build: ./dockerfiles/java8/
    image: 'poldam/java8'
    container_name: 'poldam_java8'
    working_dir: '/root/'
    tty: true
    volumes:
      - type: bind
        source: ./Data
        target: /root/selogger       

  cpp:
    restart: always
    build: ./dockerfiles/c++
    image: 'poldam/cpp'
    container_name: 'poldam_cpp'
    working_dir: '/root/'
    tty: true
    volumes:
      - type: bind
        source: .
        target: /root/POLDAM
