# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/prebe/Document/Github/POLDAM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/prebe/Document/Github/POLDAM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prebe/Document/Github/POLDAM/CMakeFiles /home/prebe/Document/Github/POLDAM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/prebe/Document/Github/POLDAM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named metafileParser

# Build rule for target.
metafileParser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 metafileParser
.PHONY : metafileParser

# fast build rule for target.
metafileParser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/build
.PHONY : metafileParser/fast

#=============================================================================
# Target rules for targets named interpreter

# Build rule for target.
interpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interpreter
.PHONY : interpreter

# fast build rule for target.
interpreter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interpreter.dir/build.make CMakeFiles/interpreter.dir/build
.PHONY : interpreter/fast

#=============================================================================
# Target rules for targets named omniGraph

# Build rule for target.
omniGraph: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omniGraph
.PHONY : omniGraph

# fast build rule for target.
omniGraph/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omniGraph.dir/build.make CMakeFiles/omniGraph.dir/build
.PHONY : omniGraph/fast

#=============================================================================
# Target rules for targets named POLDAM

# Build rule for target.
POLDAM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 POLDAM
.PHONY : POLDAM

# fast build rule for target.
POLDAM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/POLDAM.dir/build.make CMakeFiles/POLDAM.dir/build
.PHONY : POLDAM/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

Graph/src/graph.o: Graph/src/graph.cpp.o
.PHONY : Graph/src/graph.o

# target to build an object file
Graph/src/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omniGraph.dir/build.make CMakeFiles/omniGraph.dir/Graph/src/graph.cpp.o
.PHONY : Graph/src/graph.cpp.o

Graph/src/graph.i: Graph/src/graph.cpp.i
.PHONY : Graph/src/graph.i

# target to preprocess a source file
Graph/src/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omniGraph.dir/build.make CMakeFiles/omniGraph.dir/Graph/src/graph.cpp.i
.PHONY : Graph/src/graph.cpp.i

Graph/src/graph.s: Graph/src/graph.cpp.s
.PHONY : Graph/src/graph.s

# target to generate assembly for a file
Graph/src/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omniGraph.dir/build.make CMakeFiles/omniGraph.dir/Graph/src/graph.cpp.s
.PHONY : Graph/src/graph.cpp.s

Graph/src/graph_diff.o: Graph/src/graph_diff.cpp.o
.PHONY : Graph/src/graph_diff.o

# target to build an object file
Graph/src/graph_diff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omniGraph.dir/build.make CMakeFiles/omniGraph.dir/Graph/src/graph_diff.cpp.o
.PHONY : Graph/src/graph_diff.cpp.o

Graph/src/graph_diff.i: Graph/src/graph_diff.cpp.i
.PHONY : Graph/src/graph_diff.i

# target to preprocess a source file
Graph/src/graph_diff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omniGraph.dir/build.make CMakeFiles/omniGraph.dir/Graph/src/graph_diff.cpp.i
.PHONY : Graph/src/graph_diff.cpp.i

Graph/src/graph_diff.s: Graph/src/graph_diff.cpp.s
.PHONY : Graph/src/graph_diff.s

# target to generate assembly for a file
Graph/src/graph_diff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omniGraph.dir/build.make CMakeFiles/omniGraph.dir/Graph/src/graph_diff.cpp.s
.PHONY : Graph/src/graph_diff.cpp.s

Interpreter/src/event_handler.o: Interpreter/src/event_handler.cpp.o
.PHONY : Interpreter/src/event_handler.o

# target to build an object file
Interpreter/src/event_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interpreter.dir/build.make CMakeFiles/interpreter.dir/Interpreter/src/event_handler.cpp.o
.PHONY : Interpreter/src/event_handler.cpp.o

Interpreter/src/event_handler.i: Interpreter/src/event_handler.cpp.i
.PHONY : Interpreter/src/event_handler.i

# target to preprocess a source file
Interpreter/src/event_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interpreter.dir/build.make CMakeFiles/interpreter.dir/Interpreter/src/event_handler.cpp.i
.PHONY : Interpreter/src/event_handler.cpp.i

Interpreter/src/event_handler.s: Interpreter/src/event_handler.cpp.s
.PHONY : Interpreter/src/event_handler.s

# target to generate assembly for a file
Interpreter/src/event_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/interpreter.dir/build.make CMakeFiles/interpreter.dir/Interpreter/src/event_handler.cpp.s
.PHONY : Interpreter/src/event_handler.cpp.s

MetaFileParser/src/classes.o: MetaFileParser/src/classes.cpp.o
.PHONY : MetaFileParser/src/classes.o

# target to build an object file
MetaFileParser/src/classes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/classes.cpp.o
.PHONY : MetaFileParser/src/classes.cpp.o

MetaFileParser/src/classes.i: MetaFileParser/src/classes.cpp.i
.PHONY : MetaFileParser/src/classes.i

# target to preprocess a source file
MetaFileParser/src/classes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/classes.cpp.i
.PHONY : MetaFileParser/src/classes.cpp.i

MetaFileParser/src/classes.s: MetaFileParser/src/classes.cpp.s
.PHONY : MetaFileParser/src/classes.s

# target to generate assembly for a file
MetaFileParser/src/classes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/classes.cpp.s
.PHONY : MetaFileParser/src/classes.cpp.s

MetaFileParser/src/dataids.o: MetaFileParser/src/dataids.cpp.o
.PHONY : MetaFileParser/src/dataids.o

# target to build an object file
MetaFileParser/src/dataids.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/dataids.cpp.o
.PHONY : MetaFileParser/src/dataids.cpp.o

MetaFileParser/src/dataids.i: MetaFileParser/src/dataids.cpp.i
.PHONY : MetaFileParser/src/dataids.i

# target to preprocess a source file
MetaFileParser/src/dataids.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/dataids.cpp.i
.PHONY : MetaFileParser/src/dataids.cpp.i

MetaFileParser/src/dataids.s: MetaFileParser/src/dataids.cpp.s
.PHONY : MetaFileParser/src/dataids.s

# target to generate assembly for a file
MetaFileParser/src/dataids.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/dataids.cpp.s
.PHONY : MetaFileParser/src/dataids.cpp.s

MetaFileParser/src/factory.o: MetaFileParser/src/factory.cpp.o
.PHONY : MetaFileParser/src/factory.o

# target to build an object file
MetaFileParser/src/factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/factory.cpp.o
.PHONY : MetaFileParser/src/factory.cpp.o

MetaFileParser/src/factory.i: MetaFileParser/src/factory.cpp.i
.PHONY : MetaFileParser/src/factory.i

# target to preprocess a source file
MetaFileParser/src/factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/factory.cpp.i
.PHONY : MetaFileParser/src/factory.cpp.i

MetaFileParser/src/factory.s: MetaFileParser/src/factory.cpp.s
.PHONY : MetaFileParser/src/factory.s

# target to generate assembly for a file
MetaFileParser/src/factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/factory.cpp.s
.PHONY : MetaFileParser/src/factory.cpp.s

MetaFileParser/src/methods.o: MetaFileParser/src/methods.cpp.o
.PHONY : MetaFileParser/src/methods.o

# target to build an object file
MetaFileParser/src/methods.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/methods.cpp.o
.PHONY : MetaFileParser/src/methods.cpp.o

MetaFileParser/src/methods.i: MetaFileParser/src/methods.cpp.i
.PHONY : MetaFileParser/src/methods.i

# target to preprocess a source file
MetaFileParser/src/methods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/methods.cpp.i
.PHONY : MetaFileParser/src/methods.cpp.i

MetaFileParser/src/methods.s: MetaFileParser/src/methods.cpp.s
.PHONY : MetaFileParser/src/methods.s

# target to generate assembly for a file
MetaFileParser/src/methods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/methods.cpp.s
.PHONY : MetaFileParser/src/methods.cpp.s

MetaFileParser/src/object_file.o: MetaFileParser/src/object_file.cpp.o
.PHONY : MetaFileParser/src/object_file.o

# target to build an object file
MetaFileParser/src/object_file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/object_file.cpp.o
.PHONY : MetaFileParser/src/object_file.cpp.o

MetaFileParser/src/object_file.i: MetaFileParser/src/object_file.cpp.i
.PHONY : MetaFileParser/src/object_file.i

# target to preprocess a source file
MetaFileParser/src/object_file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/object_file.cpp.i
.PHONY : MetaFileParser/src/object_file.cpp.i

MetaFileParser/src/object_file.s: MetaFileParser/src/object_file.cpp.s
.PHONY : MetaFileParser/src/object_file.s

# target to generate assembly for a file
MetaFileParser/src/object_file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/object_file.cpp.s
.PHONY : MetaFileParser/src/object_file.cpp.s

MetaFileParser/src/selogger_log.o: MetaFileParser/src/selogger_log.cpp.o
.PHONY : MetaFileParser/src/selogger_log.o

# target to build an object file
MetaFileParser/src/selogger_log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/selogger_log.cpp.o
.PHONY : MetaFileParser/src/selogger_log.cpp.o

MetaFileParser/src/selogger_log.i: MetaFileParser/src/selogger_log.cpp.i
.PHONY : MetaFileParser/src/selogger_log.i

# target to preprocess a source file
MetaFileParser/src/selogger_log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/selogger_log.cpp.i
.PHONY : MetaFileParser/src/selogger_log.cpp.i

MetaFileParser/src/selogger_log.s: MetaFileParser/src/selogger_log.cpp.s
.PHONY : MetaFileParser/src/selogger_log.s

# target to generate assembly for a file
MetaFileParser/src/selogger_log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metafileParser.dir/build.make CMakeFiles/metafileParser.dir/MetaFileParser/src/selogger_log.cpp.s
.PHONY : MetaFileParser/src/selogger_log.cpp.s

Util/include/src/poldam_util.o: Util/include/src/poldam_util.cpp.o
.PHONY : Util/include/src/poldam_util.o

# target to build an object file
Util/include/src/poldam_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/Util/include/src/poldam_util.cpp.o
.PHONY : Util/include/src/poldam_util.cpp.o

Util/include/src/poldam_util.i: Util/include/src/poldam_util.cpp.i
.PHONY : Util/include/src/poldam_util.i

# target to preprocess a source file
Util/include/src/poldam_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/Util/include/src/poldam_util.cpp.i
.PHONY : Util/include/src/poldam_util.cpp.i

Util/include/src/poldam_util.s: Util/include/src/poldam_util.cpp.s
.PHONY : Util/include/src/poldam_util.s

# target to generate assembly for a file
Util/include/src/poldam_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/util.dir/build.make CMakeFiles/util.dir/Util/include/src/poldam_util.cpp.s
.PHONY : Util/include/src/poldam_util.cpp.s

Util/include/test/test_poldam_util.o: Util/include/test/test_poldam_util.cpp.o
.PHONY : Util/include/test/test_poldam_util.o

# target to build an object file
Util/include/test/test_poldam_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/Util/include/test/test_poldam_util.cpp.o
.PHONY : Util/include/test/test_poldam_util.cpp.o

Util/include/test/test_poldam_util.i: Util/include/test/test_poldam_util.cpp.i
.PHONY : Util/include/test/test_poldam_util.i

# target to preprocess a source file
Util/include/test/test_poldam_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/Util/include/test/test_poldam_util.cpp.i
.PHONY : Util/include/test/test_poldam_util.cpp.i

Util/include/test/test_poldam_util.s: Util/include/test/test_poldam_util.cpp.s
.PHONY : Util/include/test/test_poldam_util.s

# target to generate assembly for a file
Util/include/test/test_poldam_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/Util/include/test/test_poldam_util.cpp.s
.PHONY : Util/include/test/test_poldam_util.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/POLDAM.dir/build.make CMakeFiles/POLDAM.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/POLDAM.dir/build.make CMakeFiles/POLDAM.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/POLDAM.dir/build.make CMakeFiles/POLDAM.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... POLDAM"
	@echo "... interpreter"
	@echo "... metafileParser"
	@echo "... omniGraph"
	@echo "... test_util"
	@echo "... util"
	@echo "... Graph/src/graph.o"
	@echo "... Graph/src/graph.i"
	@echo "... Graph/src/graph.s"
	@echo "... Graph/src/graph_diff.o"
	@echo "... Graph/src/graph_diff.i"
	@echo "... Graph/src/graph_diff.s"
	@echo "... Interpreter/src/event_handler.o"
	@echo "... Interpreter/src/event_handler.i"
	@echo "... Interpreter/src/event_handler.s"
	@echo "... MetaFileParser/src/classes.o"
	@echo "... MetaFileParser/src/classes.i"
	@echo "... MetaFileParser/src/classes.s"
	@echo "... MetaFileParser/src/dataids.o"
	@echo "... MetaFileParser/src/dataids.i"
	@echo "... MetaFileParser/src/dataids.s"
	@echo "... MetaFileParser/src/factory.o"
	@echo "... MetaFileParser/src/factory.i"
	@echo "... MetaFileParser/src/factory.s"
	@echo "... MetaFileParser/src/methods.o"
	@echo "... MetaFileParser/src/methods.i"
	@echo "... MetaFileParser/src/methods.s"
	@echo "... MetaFileParser/src/object_file.o"
	@echo "... MetaFileParser/src/object_file.i"
	@echo "... MetaFileParser/src/object_file.s"
	@echo "... MetaFileParser/src/selogger_log.o"
	@echo "... MetaFileParser/src/selogger_log.i"
	@echo "... MetaFileParser/src/selogger_log.s"
	@echo "... Util/include/src/poldam_util.o"
	@echo "... Util/include/src/poldam_util.i"
	@echo "... Util/include/src/poldam_util.s"
	@echo "... Util/include/test/test_poldam_util.o"
	@echo "... Util/include/test/test_poldam_util.i"
	@echo "... Util/include/test/test_poldam_util.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

